import '@/app/styles/global.scss';

import { Providers } from '@/app/providers';
import { Stack } from '@mui/material';
import type { Metadata } from 'next';
import { ReactNode } from 'react';
import { ConstructorHeader } from '@/widgets/ConstructorHeader/ui/ConstructorHeader';

export const metadata: Metadata = {
    title: 'Витрина РТФ',
    description: 'Generated by create next app',
    icons: '/logo.svg',
};

interface RootLayoutProps {
    readonly children: ReactNode;
}

export default function RootLayout(props: RootLayoutProps) {
    const { children } = props;

    return (
        <html lang="ru">
            <body>
                <Providers>
                    <Stack component="main">
                        <ConstructorHeader />
                        {children}
                    </Stack>
                </Providers>
            </body>
        </html>
    );
}
