import '@/app/styles/index.scss';

import { Providers } from '@/app/providers';
import { Stack } from '@mui/material';
import type { Metadata } from 'next';
import { ReactNode } from 'react';

import { roboto, poppins, manrope, nunito } from '@/shared/fonts';

export const metadata: Metadata = {
    title: 'Витрина РТФ',
    description: 'Generated by create next app',
    icons: '/logo.svg',
};

interface RootLayoutProps {
    readonly children: ReactNode;
}

export default function RootLayout(props: RootLayoutProps) {
    const { children } = props;

    return (
        <html lang="ru" className={`${roboto.variable} ${poppins.variable} ${manrope.variable} ${nunito.variable}`}>
            <body>
                <Providers>
                    <Stack component="main">{children}</Stack>
                </Providers>
            </body>
        </html>
    );
}
