import type { Metadata } from 'next';
import '@/app/styles/index.scss';
import { ReactNode } from 'react';
import { Providers } from '@/app/providers';
import { Footer } from '@/widgets/Footer';
import styles from './layout.module.scss';
import { Stack } from '@mui/material';

export const metadata: Metadata = {
    title: 'Витрина РТФ',
    description: 'Generated by create next app',
};

interface RootLayoutProps {
    readonly children: ReactNode;
}

export default function RootLayout(props: RootLayoutProps) {
    const { children } = props;

    return (
        <html lang="ru">
            <body>
                <Providers>
                    <Stack component="main" className={styles.container}>
                        {children}
                    </Stack>
                    <Footer />
                </Providers>
            </body>
        </html>
    );
}
