import { Providers } from '@/app/providers';
import '@/app/styles/index.scss';
import { Footer } from '@/widgets/Footer';
import { Stack } from '@mui/material';
import type { Metadata } from 'next';
import { ReactNode } from 'react';
import styles from './layout.module.scss';

export const metadata: Metadata = {
    title: 'Витрина РТФ',
    description: 'Generated by create next app',
};

interface RootLayoutProps {
    readonly children: ReactNode;
}

export default function RootLayout(props: RootLayoutProps) {
    const { children } = props;

    return (
        <html lang="ru">
            <body>
                <Providers>
                    <Stack className={styles.container}>
                        <Stack component="main" className={styles.main}>
                            {children}
                        </Stack>
                        <Footer />
                    </Stack>
                </Providers>
            </body>
        </html>
    );
}
