import '@/app/styles/index.scss';

import styles from './layout.module.scss';

import type { Metadata } from 'next';
import { Stack } from '@mui/material';
import { ReactNode } from 'react';

import { Providers } from '@/app/providers';
import { Footer } from '@/widgets/Footer';

export const metadata: Metadata = {
    title: 'Витрина РТФ',
    description: 'Generated by create next app',
    icons: '/logo.svg',
};

interface RootLayoutProps {
    readonly children: ReactNode;
}

export default function RootLayout(props: RootLayoutProps) {
    const { children } = props;

    return (
        <html lang="ru">
            <body>
                <Providers>
                    <Stack className={styles.container}>
                        <Stack component="main" className={styles.main}>
                            {children}
                        </Stack>
                        <Footer />
                    </Stack>
                </Providers>
            </body>
        </html>
    );
}
