import '@/app/styles/reset.scss';
import '@/app/styles/variables.scss';

import { Providers } from '@/app/providers';
import { Stack } from '@mui/material';
import type { Metadata } from 'next';
import { ReactNode } from 'react';

export const metadata: Metadata = {
    title: 'Витрина РТФ',
    description: 'Generated by create next app',
    icons: '/logo.svg',
};

interface RootLayoutProps {
    readonly children: ReactNode;
}

export default function RootLayout(props: RootLayoutProps) {
    const { children } = props;

    return (
        <html lang="ru">
            <body>
                <Providers>
                    <Stack>
                        <Stack component="main">{children}</Stack>
                    </Stack>
                </Providers>
            </body>
        </html>
    );
}
