name: ci

# Controls when the workflow will run
on:
    # Triggers the workflow on pull request events
    pull_request:
        branches:
            - '*'

jobs:
    lint: # job name
        runs-on: ubuntu-latest # host's operating system
        steps:
            - name: Checkout commit # download the code from triggering commit
              uses: actions/checkout@v2

            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: '20.x'

            - name: Install Dependencies
              run: yarn install

            - name: Run linter
              run: yarn lint

    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout commit
              uses: actions/checkout@v2

            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: '20.x'

            - name: Install Dependencies
              run: yarn install

            - name: Run build
              run: yarn build
